Repository pedrod33/BioDrop, pull requests merged in 2021-06, with the labels that each got.

#25 New/backend register and login deliveries
  DeliveriesEngine/pom.xml
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Controller/CourierRestController.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Controller/SupervisorRestController.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Controller/VehicleRestController.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Exception/CourierEmailAndPasswordDoNotMatchException.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Exception/CourierEmailOrPhoneNumberInUseException.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Exception/SupervisorEmailIsUsedException.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Exception/SupervisorMailAndPasswordDoesNotMatchException.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Exception/SupervisorOrVehicleTypeAssociationException.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Exception/VehicleTypeIsUsedException.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Model/Courier.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Model/Delivery.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Model/Rating.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Model/Supervisor.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Model/Vehicle.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Pojo/LoginCourierPojo.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Pojo/RegisterCourierPojo.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Pojo/RegisterSupervisorPojo.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Repository/CourierRepository.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Repository/SupervisorRepository.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Repository/VehicleRepository.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Service/CourierService.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Service/CourierServiceImpl.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Service/SupervisorService.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Service/SupervisorServiceImpl.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Service/VehicleService.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/Service/VehicleServiceImpl.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/controller/CourierController.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/model/Courier.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/repository/CourierRepository.java
  DeliveriesEngine/src/main/java/pt/deliveries/deliveries_engine/utils/JsonUtil.java
  DeliveriesEngine/src/main/resources/application.properties
  DeliveriesEngine/src/test/java/pt/deliveries/deliveries_engine/Controller/CourierRestControllerTest.java
  DeliveriesEngine/src/test/java/pt/deliveries/deliveries_engine/Controller/SupervisorRestControllerTest.java
  DeliveriesEngine/src/test/java/pt/deliveries/deliveries_engine/Controller/VehicleRestControllerTest.java
  DeliveriesEngine/src/test/java/pt/deliveries/deliveries_engine/Service/CourierServiceTest.java
  DeliveriesEngine/src/test/java/pt/deliveries/deliveries_engine/Service/SupervisorServiceTest.java
  DeliveriesEngine/src/test/java/pt/deliveries/deliveries_engine/Service/VehicleServiceTest.java
Labels: backend, driver, new, task

#44 New/frontend creating api services
  BusinessInitiative/src/main/java/pt/deliveries/business_initiative/controller/AddressRestController.java
  BusinessInitiative/src/main/java/pt/deliveries/business_initiative/controller/ClientRestController.java
  BusinessInitiative/src/main/java/pt/deliveries/business_initiative/controller/OrderRestController.java
  BusinessInitiative/src/main/java/pt/deliveries/business_initiative/controller/ProductRestController.java
  BusinessInitiative/src/main/java/pt/deliveries/business_initiative/controller/StoreRestController.java
  TQS_final/ClientApp/package-lock.json
  TQS_final/ClientApp/package.json
  TQS_final/ClientApp/src/App.js
  TQS_final/ClientApp/src/components/Button/Button.css
  TQS_final/ClientApp/src/components/Button/Button.js
  TQS_final/ClientApp/src/components/Button/ButtonPending.js
  TQS_final/ClientApp/src/components/CartV2/Cart.js
  TQS_final/ClientApp/src/components/CartV2/Products.js
  TQS_final/ClientApp/src/components/Home.js
  TQS_final/ClientApp/src/components/Layout.js
  TQS_final/ClientApp/src/components/NavBar/Navbar.js
  TQS_final/ClientApp/src/components/Profile/Orders.js
  TQS_final/ClientApp/src/components/Profile/OrdersHistory.js
  TQS_final/ClientApp/src/components/Profile/Pending.js
  TQS_final/ClientApp/src/components/Profile/Profile.js
  TQS_final/ClientApp/src/components/Profile/ProfileSettings.js
  TQS_final/ClientApp/src/components/Stores.js
  TQS_final/ClientApp/src/components/Stores/Stores.js
  TQS_final/ClientApp/src/components/actions/action-types/cart-actions.js
  TQS_final/ClientApp/src/components/actions/cartActions.js
  TQS_final/ClientApp/src/components/reducers/cartReducer.js
  TQS_final/ClientApp/src/images/carrot.jpg
  TQS_final/ClientApp/src/images/continente.png
  TQS_final/ClientApp/src/images/ervilha.jpg
  TQS_final/ClientApp/src/images/item1.jpg
  TQS_final/ClientApp/src/images/pimentao.jpg
  TQS_final/ClientApp/src/images/pingo.png
  TQS_final/ClientApp/src/images/spinach.jpg
  TQS_final/ClientApp/src/index.js
  TQS_final/ClientApp/src/services/client.service.js
  TQS_final/ClientApp/yarn.lock
Labels: backend, client, frontend, new

#47 Imp/backend endpoints in business for delivers
  BusinessInitiative/src/main/java/pt/deliveries/business_initiative/controller/ClientRestController.java
  BusinessInitiative/src/main/java/pt/deliveries/business_initiative/controller/OrderRestController.java
  BusinessInitiative/src/main/java/pt/deliveries/business_initiative/exception/OrderNotFoundException.java
  BusinessInitiative/src/main/java/pt/deliveries/business_initiative/pojo/AddressPOJO.java
  BusinessInitiative/src/main/java/pt/deliveries/business_initiative/repository/OrderRepository.java
  BusinessInitiative/src/main/java/pt/deliveries/business_initiative/service/OrderService.java
  BusinessInitiative/src/main/java/pt/deliveries/business_initiative/service/OrderServiceImpl.java
  BusinessInitiative/src/main/resources/application.properties
  BusinessInitiative/src/test/java/pt/deliveries/business_initiative/controller/OrderRestController_WithMockServiceTest.java
  BusinessInitiative/src/test/java/pt/deliveries/business_initiative/service/OrderServiceTest.java
  TQS_final/ClientApp/src/components/CartV2/Cart.js
  TQS_final/ClientApp/src/components/CartV2/Products.js
  TQS_final/ClientApp/src/components/Home.js
  TQS_final/ClientApp/src/components/NavBar/Navbar.js
  TQS_final/ClientApp/src/components/Profile/OrdersHistory.js
  TQS_final/ClientApp/src/components/Profile/Pending.js
  TQS_final/ClientApp/src/components/Stores.js
  TQS_final/ClientApp/src/services/client.service.js
Labels: backend, new

#54 login, resgiter, map and card for orders
  TQS_final/RiderApp/public/images/rider.jpg
  TQS_final/RiderApp/src/App.js
  TQS_final/RiderApp/src/Rider/Rider.js
  TQS_final/RiderApp/src/components/Home.js
  TQS_final/RiderApp/src/components/Register.js
  TQS_final/RiderApp/src/components/SignIn.js
  TQS_final/RiderApp/src/components/SignUp.js
  TQS_final/RiderApp/src/services/rider.services.js
Labels: frontend, new
